# Project
version = 2.0.11
group = de.draradech.flowermap
java_version = 25

# Common
mod_author = Draradech
mod_name = Flower Map
mod_id = flowermap

# Minecraft
minecraft_version = 26.3

# NeoForm https://projects.neoforged.net/neoforged/neoform
neo_form_version = 26.3-1

# Fabric https://fabricmc.net/develop/
fabric_version = 0.160.7+26.3
fabric_loader_version = 0.19.5

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 26.3.0.3-beta

# Dependencies
clothconfig_version = 26.3.158
modmenu_version = 21.0.0-beta.1

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
